baseURL = 'http://registry-hunter.velocidex.com/'
languageCode = 'en-us'
title = 'Velociraptor Registry Hunting'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'


[params]
BookTheme = 'light'
BookSearch = false