name: Test generated artifacts

on: [pull_request]

jobs:
  build:
    name: Registry Hunter Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.20'
      id: go

    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build artifacts
      run: |
        make all recmd artifact

    - name: Run tests
      run: |
        make test

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: output
        path: output
